---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@906990fde86426c27eb355b1600afbcda8fddc25 # v4.1.5
    with:
      multi-module: true
      skip-scan: true
    secrets: inherit
