---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    # Only on main repository (don't publish on forks)
    if: github.repository_owner == 'wetransform'

    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@109404d78d84f07b3bb374a8171f8df4c13a7e88 # v4.1.4
    with:
      multi-module: true
      semantic-release: false
      skip-scan: true
    secrets: inherit
