---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
        default: false

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    # Only on main repository (don't release on forks)
    if: github.repository_owner == 'wetransform'

    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@109404d78d84f07b3bb374a8171f8df4c13a7e88 # v4.1.4
    with:
      semantic-release-dryrun: ${{ inputs.dryRun }}
      multi-module: true
      semantic-release: true
      skip-scan: true
    secrets: inherit
