---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
        default: false
      skipCheck:
        type: boolean
        description: "Skip checks/tests"
        default: false

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    # Only on main repository (don't release on forks)
    if: github.repository_owner == 'wetransform'

    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@89e3c7b982253b7195aeeae1fc2d6919a5bfa6ed # v4.2.1
    with:
      semantic-release-dryrun: ${{ github.event_name == 'workflow_dispatch' && inputs.dryRun || false }}
      skip-check: ${{ github.event_name == 'workflow_dispatch' && inputs.skipCheck || false }}
      multi-module: true
      semantic-release: true
      skip-scan: true
    secrets: inherit
